"""Measure, don't guess, the renewal cache's serve threshold and margin.

Two threshold guesses already went wrong in this codebase in opposite
directions (see answer_cache.CACHE_THRESHOLD's history) — this script exists
so CACHE_THRESHOLD_RENEWAL / CACHE_MARGIN are set from real cosine behaviour
on this corpus instead of ported from the coverage campaign's.

For each of the 126 held-out paraphrases (data/renewal/eval/paraphrases.jsonl
— NOT present in the seeded cue_variants, generated by
generate_paraphrases_renewal.py), against the seeded answer_cache_renewal:

  (i)   cosine to its OWN rule's best row      -> true-positive band
  (ii)  cosine to the best row of ANOTHER rule -> false-positive band
  (iii) cosine to the best row in the OTHER cacheable tier (T1<->T3; T2/T4
        are never in the cache at all, so any serve for a T2/T4 paraphrase
        is a cross-tier serve by construction) -> the dangerous band

Then simulates the actual serve decision (LIMIT 2, tier-crossing guard,
margin) over all 126 and reports hit rate / false-serve rate / cross-tier
count against ground truth, at a few candidate margins.

Run:  python scripts/measure_cache_bar_renewal.py
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT / ".env.kb", override=True)
load_dotenv(ROOT / ".env")

from sqlalchemy import text  # noqa: E402

from sace_chat.db import engine  # noqa: E402
from sace_chat.embeddings import embed_many, get_embedder  # noqa: E402

PARAPHRASES = ROOT / "data" / "renewal" / "eval" / "paraphrases.jsonl"
MEASURED_OUT = ROOT / "data" / "renewal" / "eval" / "cache_bar.json"
CACHEABLE_TIERS = ("T1", "T3")
MARGIN_GRID = [0.0, 0.02, 0.05, 0.08, 0.10, 0.15]


def load_paraphrases():
    rows = []
    with open(PARAPHRASES, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def summarize(label, values):
    if not values:
        print(f"  {label}: (no data)")
        return None
    vs = sorted(values)
    q = statistics.quantiles(vs, n=4) if len(vs) >= 4 else [vs[0], statistics.median(vs), vs[-1]]
    print(f"  {label}: n={len(vs)} min={vs[0]:.4f} p25={q[0]:.4f} "
          f"median={statistics.median(vs):.4f} p75={q[-1]:.4f} max={vs[-1]:.4f}")
    return vs


def main():
    paraphrases = load_paraphrases()
    embedder = get_embedder()
    vecs = embed_many(embedder, [p["paraphrase"] for p in paraphrases])  # ONE batched call
    print(f"embedder: {type(embedder).__name__}  paraphrases: {len(paraphrases)}")

    own_sims, other_sims, other_tier_sims = [], [], []
    top1_top2 = []  # (rule_id, tier, top1_sim, top1_tier, top1_rule, top2_sim, top2_tier)

    with engine.connect() as conn:
        for p, vec in zip(paraphrases, vecs):
            qvec = str(list(vec))
            rule_id, tier = p["id"], p["tier"]

            other_best = conn.execute(text(
                "SELECT 1 - MIN(embedding <=> CAST(:q AS vector)) AS sim "
                "FROM answer_cache_renewal WHERE governing_rule_id != :rid"
            ), {"q": qvec, "rid": rule_id}).scalar()
            if other_best is not None:
                other_sims.append(float(other_best))

            if tier in CACHEABLE_TIERS:
                own_best = conn.execute(text(
                    "SELECT 1 - MIN(embedding <=> CAST(:q AS vector)) AS sim "
                    "FROM answer_cache_renewal WHERE governing_rule_id = :rid"
                ), {"q": qvec, "rid": rule_id}).scalar()
                if own_best is not None:
                    own_sims.append(float(own_best))

                other_tier = [t for t in CACHEABLE_TIERS if t != tier][0]
                ot_best = conn.execute(text(
                    "SELECT 1 - MIN(embedding <=> CAST(:q AS vector)) AS sim "
                    "FROM answer_cache_renewal WHERE tier = :t"
                ), {"q": qvec, "t": other_tier}).scalar()
                if ot_best is not None:
                    other_tier_sims.append(float(ot_best))

            top2 = conn.execute(text(
                "SELECT governing_rule_id, tier, embedding <=> CAST(:q AS vector) AS distance "
                "FROM answer_cache_renewal ORDER BY distance LIMIT 2"
            ), {"q": qvec}).fetchall()
            t1 = top2[0]
            t2 = top2[1] if len(top2) > 1 else top2[0]
            top1_top2.append((rule_id, tier, 1 - float(t1.distance), t1.tier, t1.governing_rule_id,
                               1 - float(t2.distance), t2.tier))

    print("\n[distributions]")
    summarize("(i)   true-positive  (own rule)", own_sims)
    summarize("(ii)  false-positive (other rule)", other_sims)
    summarize("(iii) dangerous      (other cacheable tier)", other_tier_sims)

    gap_low = min(own_sims) if own_sims else None
    gap_high = max(other_sims) if other_sims else None
    print(f"\ngap: min(true-positive)={gap_low:.4f}  max(false-positive)={gap_high:.4f}"
          + ("  (bands separate)" if gap_low > gap_high else "  *** BANDS OVERLAP ***"))

    if gap_low > gap_high:
        threshold = (gap_low + gap_high) / 2
    else:
        threshold = (statistics.median(own_sims) + statistics.median(other_sims)) / 2
        print("!! bands overlap — falling back to a midpoint of MEDIANS, not a clean gap. "
              "Treat CACHE_THRESHOLD_RENEWAL below as provisional; this corpus needs a second look.")
    print(f"CACHE_THRESHOLD_RENEWAL (measured) = {threshold:.4f}")

    print("\n[decision simulation — threshold + LIMIT-2 tier-crossing guard + margin]")
    print(f"{'margin':>7} {'hits':>6} {'false':>6} {'cross':>6} {'miss':>6} "
          f"{'hit%':>7} {'false%':>7}")
    best_margin = None
    grid_results = []
    for margin in MARGIN_GRID:
        hits = false_serve = cross_tier = miss = 0
        for rule_id, tier, s1, t1_tier, t1_rule, s2, t2_tier in top1_top2:
            served = s1 >= threshold and t1_tier == t2_tier and (s1 - s2) >= margin
            if not served:
                miss += 1
                continue
            if t1_rule == rule_id:
                hits += 1
            elif t1_tier == tier:
                false_serve += 1
            else:
                cross_tier += 1
        n = len(top1_top2)
        hit_pct, false_pct = 100 * hits / n, 100 * false_serve / n
        grid_results.append({"margin": margin, "hits": hits, "false_serve": false_serve,
                              "cross_tier": cross_tier, "miss": miss,
                              "hit_pct": hit_pct, "false_pct": false_pct})
        print(f"{margin:>7.2f} {hits:>6} {false_serve:>6} {cross_tier:>6} {miss:>6} "
              f"{hit_pct:>6.1f}% {false_pct:>6.2f}%")
        if cross_tier == 0 and false_pct < 1.0 and best_margin is None:
            best_margin = margin

    print()
    if best_margin is not None:
        print(f"CACHE_MARGIN (measured) = {best_margin:.2f} — smallest margin in the grid with "
              f"zero cross-tier serves and false-serve rate under 1%.")
    else:
        print("!! no margin in the grid reaches zero cross-tier serves + <1% false-serve rate. "
              "Do NOT lower the margin to force a number — re-inspect the (iii) dangerous-band "
              "distribution above; the corpus likely needs more/better seeded variants for the "
              "colliding rule(s) before this is safe to serve at all.")

    MEASURED_OUT.write_text(json.dumps({
        "n_paraphrases": len(paraphrases),
        "bands": {
            "true_positive": {"n": len(own_sims), "min": min(own_sims), "max": max(own_sims)},
            "false_positive": {"n": len(other_sims), "min": min(other_sims), "max": max(other_sims)},
            "dangerous_other_tier": {"n": len(other_tier_sims), "min": min(other_tier_sims),
                                      "max": max(other_tier_sims)},
        },
        "cache_threshold_renewal": round(threshold, 4),
        "cache_margin": best_margin,
        "grid": grid_results,
    }, indent=2), encoding="utf-8")
    print(f"\nwrote {MEASURED_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
